name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html requests schemathesis

    - name: Run pytest and generate HTML report
      run: pytest st_demo.py --html=report.html

    - name: Upload HTML report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: HTML Report
        path: report.html
